### PR TITLE
359 😛

### PR DESCRIPTION
**Pull request by p01**
If we can't use `x:_%80;y:_\80` then let's use `x:_%128;y:_>>7` and pad the textarea instead.

Once we finalize the quine, we can use 64 characters wide to save one extra byte by using `x:_%64,y:y>>6`

### CODE REVIEW

**Comment by xem** [comment]
Wow good idea...
Here's a sneak peek of my quine maker
image
(In the end, I'll eval the code after applying a `.replace(/  +/g, "")` and replacing O.value with something that makes a real quine). Then I'll change the shape a little so it's 64 chars wide and not too tall.)

**Comment by p01** [comment]
Oh! Nice you automated the transformation of the code to match the ASCII art of the shape.
I'll try to create a 64x?? shape that works well with the size of the code of our fluid simulation

**Comment by xem** [comment]
Sure, I'll try to make one too. I doubt the whole thing can fit in 1kb, unless we make another shape, one that does not spell "fluid"? All ideas are welcome, many examples are available from endoh1-ts in the /inputs folder

**Comment by p01** [comment]
Yeah,  stretching out ~356bytes of code across 64bytes wide lines with mandatory whitespace + the receiving shape probably won't fit in 1kb.

This 64x20 shape takes ~1400 bytes 😯

```
        @@@@@@@@  @@@@                                         
       @@@@@@@@   @@@@                                         
       @@@@       @@@@                    @@@         @@@@     
       @@@@       @@@@                   @@@@         @@@@     
       @@@@       @@@@                   @@@          @@@@     
       @@@@       @@@@                                @@@@     
     @@@@@@@@@    @@@@    @@@@    @@@@   @@@@     @@@@@@@@     
    @@@@@@@@@     @@@@    @@@@    @@@@   @@@@   @@@@@@@@@@     
       @@@@       @@@@    @@@@    @@@@   @@@@   @@@@  @@@@     
       @@@@       @@@@    @@@@    @@@@   @@@@   @@@@  @@@@     
       @@@@       @@@@    @@@@    @@@@   @@@@   @@@@  @@@@     
       @@@@       @@@@    @@@@    @@@@   @@@@   @@@@  @@@@     
       @@@@       @@@@    @@@@    @@@@   @@@@   @@@@  @@@@     
       @@@@       @@@@@   @@@@@@@@@@@@   @@@@   @@@@@@@@@@     
      @@@@         @@@@@   @@@@@@@@@@@   @@@@    @@@@@@@@@     
##                                                           ##
##                                                           ##
##                                                           ##
##                                                           ##
##                                                           ##
###                                                         ###
 #############################################################
```

**Comment by xem** [comment]
Great!
I made it bolder and lower: 416 @'s for a total of 947 bytes (made it quickly, the style can be improved)
```
       @@@@@@@@@  @@@@@                               @@@@@               
      @@@@@@@@@   @@@@@                 @@@@@         @@@@@
      @@@@@       @@@@@                 @@@@@         @@@@@
      @@@@@       @@@@@                               @@@@@
    @@@@@@@@@@    @@@@@   @@@@@  @@@@@  @@@@@     @@@@@@@@@
   @@@@@@@@@@     @@@@@   @@@@@  @@@@@  @@@@@   @@@@@@@@@@@
      @@@@@       @@@@@   @@@@@  @@@@@  @@@@@  @@@@@@@@@@@@
      @@@@@       @@@@@   @@@@@  @@@@@  @@@@@  @@@@@  @@@@@
      @@@@@       @@@@@   @@@@@  @@@@@  @@@@@  @@@@@  @@@@@
      @@@@@       @@@@@   @@@@@  @@@@@  @@@@@  @@@@@  @@@@@
##    @@@@@       @@@@@   @@@@@@@@@@@@  @@@@@  @@@@@@@@@@@@  ##
##    @@@@@       @@@@@@  @@@@@@@@@@@@  @@@@@   @@@@@@@@@@@  ##
##   @@@@@         @@@@@@  @@@@@@@@@@@  @@@@@@   @@@@@@@@@@  ##
###                                                         ###
 #############################################################
```

**Comment by p01** [comment]
Here's one in 40x21 which takes 878 bytes, and surely we can trim 40-80 bytes from the receiving shape.
It looks like we can git the Quine Fluid sim in 1kb after all.
```
   @@@@@@ @@@  @@@   @@@ @@@ @@@@@@@   
  @@@@@@@ @@@  @@@   @@@ @@@ @@@@@@@@  
  @@@@@@@ @@@  @@@   @@@ @@@ @@@@@@@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@@@@  @@@  @@@   @@@ @@@ @@@  @@@  
 @@@@@@@  @@@  @@@   @@@ @@@ @@@  @@@  
 @@@@@@@  @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@  @@@   @@@ @@@ @@@  @@@  
  @@@     @@@@ @@@@@@@@@ @@@ @@@@@@@@  
  @@@     @@@@ @@@@@@@@@ @@@ @@@@@@@@  
  @@@      @@@  @@@@@@@@ @@@ @@@@@@@   
#                                     #
#                                     #
#                                     #
#                                     #
#                                     #
##                                   ##
 #####################################
```

**Comment by xem** [comment]
nice, but it's a bit strange to have a lowercase "fl" and an uppercase "UID".
also, we need more @'s  (there are 357 @'s here, I think we'll need a total of ~400 to include the quine's overhead)

**Comment by p01** [comment]
True about the overhead of the quine. Anyhow, by the look of these early ascii "art", we should be able to fit a quine fluid simulation in 1kb 🎉

**Comment by aemkei** [comment]
```
     @@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@@@@@
    @@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@@@@@@@
    @@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@ @@@@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@  @@@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
   @@@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
   @@@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@  @@@@@
    @@@@      @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@ @@@@@@
    @@@@      @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@@@@@@@
    @@@@       @@@@@@@   @@@@@@@@@@   @@@@  @@@@@@@@     
##                                                      ##
##                                                      ##
###                                                    ###
 ########################################################
```

416 / 959

**Comment by aemkei** [comment]
Or maybe something more fluid…

```
     @@@@@@@@@@@@
    @@@@@@@@@@@@@@
    @@@@@@    @@@@
    @@@@              @@@@@     @@@@  @@@@  @@@@@@@
    @@@@      @@@@   @@@@@@@    @@@@  @@@@  @@@@ @@@@
    @@@@      @@@@      @@@@    @@@@        @@@@  @@@@
@@@@@@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
@@@@@@@@@@@@  @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
    @@@@      @@@@   @  @@@@    @@@@  @@@@  @@@@  @@@@@
    @@@@      @@@@  @@  @@@@@@@@@@@@  @@@@  @@@@ @@@@@@
    @@@@      @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@@@@@@@
    @@@@      @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@@@@@@
    @@@@       @@@@@@    @@@@@@@@@@   @@@@  @@@@@@@@     
##                                                      ##
##                                                      ##
###                                                    ###
 ########################################################
```

**Comment by aemkei** [comment]
Even more like a drop:

```
     @@@@@@@@@@@@
    @@@@@@@@@@@@@@
    @@@@@@    @@@@
    @@@@              @@@@@     @@@@   @@   @@@@@@@
    @@@@       @@    @@@@@@@    @@@@  @@@@  @@@@ @@@@
    @@@@       @@@   @  @@@@    @@@@        @@@@  @@@@
@@@@@@@@@@@@  @@@@      @@@@    @@@@   @@   @@@@   @@@@
@@@@@@@@@@@@  @@@@      @@@@    @@@@   @@@  @@@@   @@@@
    @@@@      @@@@      @@@@    @@@@  @@@@  @@@@   @@@@
   @@@@@      @@@@   @  @@@@    @@@@  @@@@  @@@@  @@@@@
   @@@@@@     @@@@  @@  @@@@@@@@@@@@  @@@@  @@@@ @@@@@@
   @@@@@@@    @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@@@@@@@
   @@@@@@@    @@@@@@@@  @@@@@@@@@@@@  @@@@  @@@@@@@@@
    @@@@@      @@@@@@    @@@@@@@@@@   @@@@  @@@@@@@       
##                                                      ##
##                                                      ##
###                                                    ###
 ########################################################
```

**Pull request merged**
